version: "2"
services:
  ### POSTGRES ###
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
    restart: always